// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Platform-specific Firebase configuration generated by `flutterfire configure`.
///
/// The values must be replaced with the Firebase project's configuration by
/// running `flutterfire configure` before building the application.
class DefaultFirebaseOptions {
  const DefaultFirebaseOptions._();

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux. '
          'Run flutterfire configure to add support.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // These sentinels deliberately keep the generated file compilable while
  // making an incomplete FlutterFire setup immediately identifiable. Running
  // `flutterfire configure` replaces them with the real project values.

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDa1LwunxxK321S1CqkSupOg9GwQE2dbJc',
    appId: '1:109593374629:web:59ba4a05001ee0f36b024c',
    messagingSenderId: '109593374629',
    projectId: 'harikyu-lab',
    authDomain: 'harikyu-lab.firebaseapp.com',
    storageBucket: 'harikyu-lab.firebasestorage.app',
    measurementId: 'G-2YVJ01DCX6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsBrqMNtNZZpdLEBdxUjzvhQDa4nr-psg',
    appId: '1:109593374629:android:9a336fe39032fc136b024c',
    messagingSenderId: '109593374629',
    projectId: 'harikyu-lab',
    storageBucket: 'harikyu-lab.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsBO5glMXNvYZSOBRjJ8okFr5szE7Z6p8',
    appId: '1:109593374629:ios:72965d09d2f10ce36b024c',
    messagingSenderId: '109593374629',
    projectId: 'harikyu-lab',
    storageBucket: 'harikyu-lab.firebasestorage.app',
    iosBundleId: 'com.harikyulab.harikyuLab',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsBO5glMXNvYZSOBRjJ8okFr5szE7Z6p8',
    appId: '1:109593374629:ios:72965d09d2f10ce36b024c',
    messagingSenderId: '109593374629',
    projectId: 'harikyu-lab',
    storageBucket: 'harikyu-lab.firebasestorage.app',
    iosBundleId: 'com.harikyulab.harikyuLab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDa1LwunxxK321S1CqkSupOg9GwQE2dbJc',
    appId: '1:109593374629:web:af6d78c182e481e86b024c',
    messagingSenderId: '109593374629',
    projectId: 'harikyu-lab',
    authDomain: 'harikyu-lab.firebaseapp.com',
    storageBucket: 'harikyu-lab.firebasestorage.app',
    measurementId: 'G-GPPG5DGJG1',
  );
}
