import 'package:flutter/material.dart';
import 'package:harikyu_lab/core/constants/app_colors.dart';
import 'package:harikyu_lab/core/constants/app_constants.dart';
import 'package:harikyu_lab/core/theme/app_theme_extension.dart';

abstract final class AppTheme {
  static const _lightScheme = ColorScheme(
    brightness: Brightness.light,
    primary: AppColors.primary,
    onPrimary: Colors.white,
    primaryContainer: AppColors.selected,
    onPrimaryContainer: AppColors.textPrimary,
    secondary: AppColors.primaryDark,
    onSecondary: Colors.white,
    secondaryContainer: AppColors.secondaryContainer,
    onSecondaryContainer: AppColors.textPrimary,
    tertiary: AppColors.success,
    onTertiary: Colors.white,
    tertiaryContainer: AppColors.tertiaryContainer,
    onTertiaryContainer: AppColors.textPrimary,
    error: AppColors.error,
    onError: Colors.white,
    errorContainer: AppColors.errorContainer,
    onErrorContainer: AppColors.onErrorContainer,
    surface: AppColors.surface,
    onSurface: AppColors.textPrimary,
    surfaceContainerLowest: Colors.white,
    surfaceContainerLow: AppColors.surface,
    surfaceContainer: AppColors.surfaceContainer,
    surfaceContainerHigh: AppColors.surfaceContainerHigh,
    surfaceContainerHighest: AppColors.subtle,
    onSurfaceVariant: AppColors.textSecondary,
    outline: AppColors.outline,
    outlineVariant: AppColors.outlineVariant,
    shadow: AppColors.shadow,
    scrim: Colors.black54,
    inverseSurface: AppColors.textPrimary,
    onInverseSurface: AppColors.surface,
    inversePrimary: AppColors.primaryLight,
  );

  static final light = ThemeData(
    useMaterial3: true,
    colorScheme: _lightScheme,
    scaffoldBackgroundColor: AppColors.background,
    canvasColor: AppColors.background,
    disabledColor: AppColors.textSecondary.withValues(alpha: .45),
    appBarTheme: const AppBarTheme(
      centerTitle: false,
      elevation: 0,
      backgroundColor: AppColors.background,
      foregroundColor: AppColors.textPrimary,
      surfaceTintColor: Colors.transparent,
      scrolledUnderElevation: 0,
      iconTheme: IconThemeData(color: AppColors.primaryDark),
      actionsIconTheme: IconThemeData(color: AppColors.primaryDark),
      titleTextStyle: TextStyle(color: AppColors.textPrimary, fontSize: 22, fontWeight: FontWeight.w800),
    ),
    cardTheme: CardThemeData(
      elevation: 0,
      color: AppColors.surface,
      surfaceTintColor: Colors.transparent,
      margin: EdgeInsets.zero,
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(AppConstants.cardRadius),
        side: const BorderSide(color: AppColors.outline),
      ),
    ),
    navigationBarTheme: NavigationBarThemeData(
      height: 76,
      elevation: 0,
      backgroundColor: AppColors.surface,
      indicatorColor: AppColors.selected,
      surfaceTintColor: Colors.transparent,
      indicatorShape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
      iconTheme: WidgetStateProperty.resolveWith((states) => IconThemeData(
        color: states.contains(WidgetState.selected) ? AppColors.primaryDark : AppColors.textSecondary,
      )),
      labelTextStyle: WidgetStateProperty.resolveWith((states) => TextStyle(
        fontSize: 11,
        fontWeight: states.contains(WidgetState.selected) ? FontWeight.w700 : FontWeight.w500,
        color: states.contains(WidgetState.selected) ? AppColors.primaryDark : AppColors.textSecondary,
      )),
    ),
    navigationRailTheme: const NavigationRailThemeData(
      backgroundColor: AppColors.surface,
      selectedIconTheme: IconThemeData(color: AppColors.primaryDark),
      unselectedIconTheme: IconThemeData(color: AppColors.textSecondary),
      selectedLabelTextStyle: TextStyle(color: AppColors.primaryDark, fontWeight: FontWeight.w700),
      unselectedLabelTextStyle: TextStyle(color: AppColors.textSecondary),
      indicatorColor: AppColors.selected,
    ),
    bottomNavigationBarTheme: const BottomNavigationBarThemeData(
      backgroundColor: AppColors.surface,
      selectedItemColor: AppColors.primaryDark,
      unselectedItemColor: AppColors.textSecondary,
      type: BottomNavigationBarType.fixed,
      elevation: 0,
    ),
    filledButtonTheme: FilledButtonThemeData(style: FilledButton.styleFrom(
      minimumSize: const Size.fromHeight(54),
      backgroundColor: AppColors.primary,
      foregroundColor: Colors.white,
      disabledBackgroundColor: AppColors.outline,
      disabledForegroundColor: AppColors.textSecondary,
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(AppConstants.controlRadius)),
      textStyle: const TextStyle(fontWeight: FontWeight.w700),
    )),
    elevatedButtonTheme: ElevatedButtonThemeData(style: ElevatedButton.styleFrom(
      backgroundColor: AppColors.primary,
      foregroundColor: Colors.white,
      surfaceTintColor: Colors.transparent,
      shadowColor: AppColors.shadow,
      minimumSize: const Size.fromHeight(54),
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(AppConstants.controlRadius)),
      textStyle: const TextStyle(fontWeight: FontWeight.w700),
    )),
    outlinedButtonTheme: OutlinedButtonThemeData(style: OutlinedButton.styleFrom(
      foregroundColor: AppColors.primaryDark,
      side: const BorderSide(color: AppColors.primary),
      minimumSize: const Size.fromHeight(48),
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(AppConstants.controlRadius)),
      textStyle: const TextStyle(fontWeight: FontWeight.w700),
    )),
    textButtonTheme: TextButtonThemeData(style: TextButton.styleFrom(
      foregroundColor: AppColors.primaryDark,
      textStyle: const TextStyle(fontWeight: FontWeight.w700),
    )),
    floatingActionButtonTheme: const FloatingActionButtonThemeData(
      backgroundColor: AppColors.primary,
      foregroundColor: Colors.white,
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.all(Radius.circular(18))),
    ),
    switchTheme: SwitchThemeData(
      thumbColor: WidgetStateProperty.resolveWith((states) => states.contains(WidgetState.selected) ? AppColors.surface : AppColors.textSecondary),
      trackColor: WidgetStateProperty.resolveWith((states) => states.contains(WidgetState.selected) ? AppColors.primary : AppColors.outline),
    ),
    checkboxTheme: CheckboxThemeData(fillColor: WidgetStateProperty.resolveWith((states) => states.contains(WidgetState.selected) ? AppColors.primary : AppColors.surface), checkColor: const WidgetStatePropertyAll(Colors.white)),
    radioTheme: RadioThemeData(fillColor: WidgetStateProperty.resolveWith((states) => states.contains(WidgetState.selected) ? AppColors.primary : AppColors.textSecondary)),
    sliderTheme: SliderThemeData(activeTrackColor: AppColors.primary, inactiveTrackColor: AppColors.outline, thumbColor: AppColors.primaryDark, overlayColor: AppColors.primary.withValues(alpha: .12)),
    progressIndicatorTheme: const ProgressIndicatorThemeData(color: AppColors.primary, linearTrackColor: AppColors.outline, circularTrackColor: AppColors.outline),
    chipTheme: ChipThemeData(
      backgroundColor: AppColors.surfaceContainerHighest,
      selectedColor: AppColors.selected,
      disabledColor: AppColors.outline,
      side: const BorderSide(color: AppColors.outline),
      labelStyle: const TextStyle(color: AppColors.textPrimary),
      secondaryLabelStyle: const TextStyle(color: AppColors.textPrimary),
      iconTheme: const IconThemeData(color: AppColors.primaryDark),
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(14)),
    ),
    dialogTheme: DialogThemeData(backgroundColor: AppColors.surface, surfaceTintColor: Colors.transparent, shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(28))),
    bottomSheetTheme: const BottomSheetThemeData(backgroundColor: AppColors.surface, surfaceTintColor: Colors.transparent, modalBackgroundColor: AppColors.surface),
    snackBarTheme: SnackBarThemeData(backgroundColor: AppColors.textPrimary, contentTextStyle: const TextStyle(color: AppColors.surface), actionTextColor: AppColors.primaryLight, behavior: SnackBarBehavior.floating, shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16))),
    inputDecorationTheme: InputDecorationTheme(
      filled: true,
      fillColor: AppColors.surface,
      contentPadding: const EdgeInsets.symmetric(horizontal: 18, vertical: 18),
      prefixIconColor: AppColors.primaryDark,
      suffixIconColor: AppColors.primaryDark,
      labelStyle: const TextStyle(color: AppColors.textSecondary),
      hintStyle: const TextStyle(color: AppColors.textSecondary),
      border: OutlineInputBorder(borderRadius: BorderRadius.circular(16)),
      enabledBorder: OutlineInputBorder(borderRadius: BorderRadius.circular(16), borderSide: const BorderSide(color: AppColors.outline)),
      focusedBorder: OutlineInputBorder(borderRadius: BorderRadius.circular(16), borderSide: const BorderSide(color: AppColors.primary, width: 2)),
    ),
    dropdownMenuTheme: DropdownMenuThemeData(inputDecorationTheme: InputDecorationTheme(filled: true, fillColor: AppColors.surface, enabledBorder: OutlineInputBorder(borderRadius: BorderRadius.circular(16), borderSide: const BorderSide(color: AppColors.outline)))),
    popupMenuTheme: PopupMenuThemeData(color: AppColors.surface, surfaceTintColor: Colors.transparent, shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(18))),
    segmentedButtonTheme: SegmentedButtonThemeData(style: SegmentedButton.styleFrom(backgroundColor: AppColors.surface, foregroundColor: AppColors.textPrimary, selectedBackgroundColor: AppColors.selected, selectedForegroundColor: AppColors.primaryDark, side: const BorderSide(color: AppColors.outline))),
    tabBarTheme: const TabBarThemeData(labelColor: AppColors.primaryDark, unselectedLabelColor: AppColors.textSecondary, indicatorColor: AppColors.primary, dividerColor: AppColors.outline),
    datePickerTheme: DatePickerThemeData(backgroundColor: AppColors.surface, surfaceTintColor: Colors.transparent, headerBackgroundColor: AppColors.primary, headerForegroundColor: Colors.white, todayForegroundColor: const WidgetStatePropertyAll(AppColors.primaryDark), todayBorder: const BorderSide(color: AppColors.primary), dayBackgroundColor: WidgetStateProperty.resolveWith((states) => states.contains(WidgetState.selected) ? AppColors.primary : null), dayForegroundColor: WidgetStateProperty.resolveWith((states) => states.contains(WidgetState.selected) ? Colors.white : AppColors.textPrimary)),
    iconTheme: const IconThemeData(color: AppColors.primaryDark),
    badgeTheme: const BadgeThemeData(backgroundColor: AppColors.primaryDark, textColor: Colors.white),
    dividerTheme: const DividerThemeData(color: AppColors.outline, thickness: 1),
    splashFactory: InkSparkle.splashFactory,
    extensions: const [AppSurfaceTheme(subtle: AppColors.subtle, success: AppColors.success, warning: AppColors.warning)],
    pageTransitionsTheme: const PageTransitionsTheme(builders: {
      TargetPlatform.iOS: CupertinoPageTransitionsBuilder(),
      TargetPlatform.android: FadeForwardsPageTransitionsBuilder(),
    }),
  );

  static final dark = light.copyWith(
    brightness: Brightness.dark,
    colorScheme: _lightScheme.copyWith(
      brightness: Brightness.dark,
      surface: AppColors.darkSurface,
      onSurface: AppColors.darkOnSurface,
      surfaceContainerLowest: AppColors.darkBackground,
      surfaceContainerLow: AppColors.darkSurface,
      surfaceContainer: AppColors.darkSurfaceContainer,
      surfaceContainerHigh: AppColors.darkSurfaceContainer,
      surfaceContainerHighest: AppColors.darkSurfaceContainer,
      onSurfaceVariant: AppColors.darkOnSurfaceVariant,
      outline: AppColors.darkOutline,
      outlineVariant: AppColors.darkOutline,
      primaryContainer: AppColors.primaryDark,
      onPrimaryContainer: AppColors.darkOnSurface,
      secondaryContainer: AppColors.darkSurfaceContainer,
      onSecondaryContainer: AppColors.darkOnSurface,
    ),
    scaffoldBackgroundColor: AppColors.darkBackground,
    canvasColor: AppColors.darkBackground,
    appBarTheme: light.appBarTheme.copyWith(
      backgroundColor: AppColors.darkBackground,
      foregroundColor: AppColors.darkOnSurface,
      titleTextStyle: light.appBarTheme.titleTextStyle?.copyWith(color: AppColors.darkOnSurface),
    ),
    cardTheme: light.cardTheme.copyWith(color: AppColors.darkSurface),
  );
}
